### ISSUE TITLE
Errors searching for libcef

### ISSUE THREAD

**Issue by HamishTPB** [bazukas/obs-linuxbrowser#25]
```
error: Required module function 'obs_module_load' in module '/usr//lib/obs-plugins/libcef.so' not found, loading of module failed
libDeckLinkAPI.so: cannot open shared object file: No such file or directory

```
Not sure if this is related to other issues or not but I get this error when I run OBS from console (note the two // between "usr//lib" in the error)

**Comment by HamishTPB** [comment]
``libDeckLinkAPI.so: cannot open shared object file: No such file or directory``
Appears when I uninstall obs-linuxbrowser now and still freezes on exit - removed all scenes/sources related to obs-linuxbrowser.

**Comment by bazukas** [comment]
Hello, here is what happens:
1. You most likely installed plugin using aur package, that package installs the plugin files not in home directory, but in global dirs
2. obs on startup goes through all /usr/lib/obs-plugins/*.so files and looks for 'obs_module_load' symbol in them, since it tries to load the plugins
3. Because libcef.so is not an obs plugin, obs shows this error

This means that there's nothing wrong going on, shouldn't worry about that.

**Comment by HamishTPB** [comment]
Ah, ok matey, thanks.
