### ISSUE TITLE
Site is not loading, Linux Mint 17.3

### ISSUE THREAD

**Issue by anarchist912** [bazukas/obs-linuxbrowser#30]
Hi bazukas! Thanks for creating this plugin for OBS Studio!

Unfortunately it does not (yet) work on my Linux Mint Cinnamon 17.3 64-bit. 

So far I cannot even display a site like http://startpage.com. It remains black. I have the same log entries as Egor initally had here: https://github.com/bazukas/obs-linuxbrowser/issues/7

I tried to get a solution from your correspondence but failed so far. I tried building it myself but gave up quickly, as Im completely new to that.

So, would you pleaaase help me, as well, bazukas? :)

[obs-log.txt](https://github.com/bazukas/obs-linuxbrowser/files/1193578/obs-log.txt)

**Comment by bazukas** [comment]
Hello, the problem is that the plugin has been compiled against newer version of glibc (Ubuntu 16.04)
I see 3 possible solutions:
1. Try to upgrade your glibc package (either from official repos if available or other means)
2. Upgrade your OS
3. Wait for me to try to compile against older version of glibc

**Comment by anarchist912** [comment]
Thanks bazukus for your quick reply.

I chose option #2 and it works now. Wanted to avoid it, cause 18.2 runs with issues, but it's okay. Thanks!

**Comment by MichaelTunnell** [comment]
unfortunately the only way to solve issues like that with Mint is to update the system because Mint only updates glibc once every 2 years.
